- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: test
    password: admin123
    url: http://172.31.91.42:8080
    user: admin
