- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.91.42:8080
    user: admin
  loop:
    - CI-Pipelines

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/s-pipeline.xml') }}"
    name: "CI-Pipelines/test"
    password: admin123
    url: http://172.31.91.42:8080
    user: admin

