- name: Create Job Template
  ansible.builtin.template:
    src: s-pipeline.xml
    dest: /tmp/s-pipeline.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-pipeline.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.12.47:8080
    user: admin